### PR TITLE
Add README.md

### PR DESCRIPTION
**Pull request by raboof**
With link to HTML version of the wiki

### CODE REVIEW

**Comment by sjoerdtimmer** [comment]
There is a delicate hooking system in place between the webserver and the github repo. 
changes should be pushed to the repo at wiki@wiki.hackerspacenijmegen.nl:wiki
Changes pushed to that repo will be pushed to github automatically but not vice versa.

@stef: what would happen if we merge this? I guess the push script will break next time someone pushes to your repo? Or does it do git pull before accepting commits from others?

**Comment by sjoerdtimmer** [comment]
Yes it would be but that requires a little extra work that hasn't been done
yet.
It requires webhooks to trigger a pull from the webserver whenever
something is pushed to github.
It sounds feasible but I don't have access to the machine in question.
@Stf: do you? What server is that actually? Is that yours? Can I get access
to setup a webhook?

**Comment by stef** [comment]
> @stef: what would happen if we merge this? I guess the push script will break next time someone pushes to your repo?

yes it would break. currently the wiki does only push to github but not pull.

**Comment by stef** [comment]
> Hmm it would be really nice if contributions could be accepted via github as well...

while this provides some convenience, it also requires some infrastructure at the wiki itself, which increases the attack surface significantly. i don't see how this attack surface increase is proportional to the convenience provided by github merged pull requests. github also provides the possibility to use "command line instructions" for merging PRs, which allow people with write access to the master git repo to merge PRs manually and push them to the master git repo. which i'll demonstrate in a few seconds ;)

**Comment by stef** [comment]
> It sounds feasible but I don't have access to the machine in question. @Stf: do you? What server is that actually? Is that yours? Can I get access to setup a webhook?

yes i have access, i pay for it. setting up a webhook correctly is a bit more work if we don't want to increase the attack surface of that server. we need some kind of authentication mechanism, and some kind of minimal trigger while avoiding setting up some kind of uwsgi/cgi/etc server side scripting environment. i've already looked if there is some kind of webhook module for nginx but did not find anything suitable. what is your idea of setting up this webhook in a way that minimizes exposure?

**Comment by stef** [comment]
pls observe a github PR merged manually without webhooks ^^^
\o/

**Comment by raboof** [comment]
A minimal way to do it might be to update the script to pull+push instead of just push. Instead of a webhook you could then just run it periodically from cron - not as nice (some delay in getting updates from github), but should work right?

There is of course then a risk that changes on the server and changes on github conflict, but given that wiki write traffic is low the chance of that might be low enough that resolving those manually might be fine?

For 'casual' contributors already comfortable with github, being able to propose updates to the wiki as pull requests is a lot easier than requesting access, cloning and pushing changes like that...

**Comment by sjoerdtimmer** [comment]
You could do the pull from github in the hook that also executes the
mkdocs. Currently if mkdocs fails the push is rejected. The same could go
for git. If the new push does not auto-merge with anything pulled
(on-the-fly) from github the push is rejected with a message that the user
should first merge with the github remote... That way no open ports for
github hooks are required at all (no cgi, no php, no nginx)

My previous idea was just a python(or even bash+nc) script that executes
"git pull" whenever it receives a http request. That should have minimal
changes on who could do what in terms of possible attack vectors. But the
first proposal in this mail sounds better.

Sjoerd

**Pull request merged**
